### ISSUE TITLE
Is this project still active now that Black Pepper Software is closed down?

### ISSUE THREAD

**Issue by mjustin** [hdpe/bowman#41]
There have not been any updates to this project in over two years, and the company that this project seems to be associated with (Black Pepper Software) no longer exists.  Is this project still active, or is it now a dead project?

[Black Pepper Software](https://blackpepper.co.uk/)

> A few months ago, we made the difficult decision to close down Black Pepper in August.

**Comment by hdpe** [comment]
Yes - I (currently) intend to continue to maintain this, respond to issues and review PRs.

The lack of development recently just reflects the lack of raised issues or PRs and that I don't use this library day-to-day.

Thanks for raising this and your other issue.
